package com.example.tapplecompanion

val tappleTopics = listOf(
    "Eläin",
    "Hedelmä",
    "Vihannes",
    "Maa",
    "Kaupunki",
    "Urheilulaji",
    "Harrastus",
    "Ammatti",
    "Asia keittiössä",
    "Asia kylpyhuoneessa",
    "Asia makuuhuoneessa",
    "Asia koulussa",
    "Asia toimistossa",
    "Huonekalu",
    "Kodinkone",
    "Ruokalaji",
    "Jälkiruoka",
    "Juoma",
    "Asia, jota syödään aamupalalla",
    "Asia, jota löytyy jääkaapista",
    "Asia rannalla",
    "Asia metsässä",
    "Asia kaupungissa",
    "Asia maaseudulla",
    "Asia lomalla",
    "Asia lentokentällä",
    "Ajoneuvo",
    "Auton merkki",
    "Asia, joka liikkuu nopeasti",
    "Asia, joka on hidas",
    "Jotain kylmää",
    "Jotain kuumaa",
    "Jotain pyöreää",
    "Jotain pehmeää",
    "Jotain kovaa",
    "Jotain äänekästä",
    "Jotain hiljaista",
    "Jotain kallista",
    "Jotain halpaa",
    "Jotain vanhaa",
    "Jotain uutta",
    "Jotain rikkinäistä",
    "Jotain hyödyllistä",
    "Jotain turhaa",
    "Jotain, mikä tekee ihmiset iloisiksi",
    "Jotain, mikä ärsyttää",
    "Jotain, mikä pelottaa",
    "Jotain, mikä naurattaa",
    "Jotain, mikä haisee pahalta",
    "Jotain, mikä tuoksuu hyvältä",
    "Jotain, mitä ei saisi tehdä",
    "Jotain, mitä tehdään viikonloppuna",
    "Jotain, mitä tehdään aamulla",
    "Jotain, mitä tehdään illalla",
    "Jotain, mitä tehdään lomalla",
    "Jotain ulkona",
    "Jotain sisällä",
    "Jotain taskuun mahtuvaa",
    "Jotain raskasta",
    "Jotain kevyttä",
    "Jotain ilmastoystävällistä",
    "Jotain ympäristölle haitallista",
    "Jotain kierrätettävää",
    "Jotain muovista",
    "Jotain metallista",
    "Jotain puusta",
    "Jotain, joka kuluttaa sähköä",
    "Jotain, joka säästää energiaa",
    "Jotain, joka tarvitsee paristoja",
    "Jotain, joka toimii ilman sähköä",
    "Jotain, mikä löytyy taskusta",
    "Jotain, mikä löytyy laukusta",
    "Jotain, mikä löytyy laatikosta",
    "Jotain, mikä unohtuu helposti",
    "Jotain, mikä katoaa helposti",
    "Jotain, mitä käytetään päivittäin",
    "Jotain, mitä käytetään harvoin",
    "Jotain, mikä maksaa alle euron",
    "Jotain, mikä maksaa paljon",
    "Jotain, mikä on kiellettyä lapsilta",
    "Jotain, mikä on vaarallista",
    "Jotain, mikä on turvallista",
    "Jotain, mikä liittyy teknologiaan",
    "Jotain, mikä liittyy luontoon",
    "Jotain, mikä liittyy juhliin",
    "Jotain, mikä liittyy urheiluun",
    "Jotain, mikä liittyy musiikkiin",
    "Jotain, mikä liittyy elokuviin",
    "Jotain, mikä liittyy matkustamiseen",
    "Jotain, mitä löytyy Suomesta"
)